# agregar todas las columnas de un archivo pagos que se utilicen
COL_TIPO_LOTE = "LOTE_TIPO"
COL_NUM_LOTE = "LOTE_NUMERO"
COL_NUM_RECIBO = "RECIBO"
COL_FECHA_COBRO = "FECHA_COBRO"
COL_IMPORTE = "IMPORTE"
COL_JUZGADO = "JUZGADO"
COL_ANIO_EXP = "CAUSA_ANIO"
COL_EXP = "CAUSA_NUMERO"
COL_OFICINA_COD = "OFICINA_CODIGO"
COL_NUM_ACTA = "ACTA_NUMERO"
COL_FECHA_LABRADA = "LABRADA_FECHA"
COL_DOC_INFRACTOR = "PERSONA_DOC"
COL_NOMBRE_INFRACTOR = "INFRACTOR"
COL_PADRON = "PADRON"  

COLUMNAS_PAGOS = [
    COL_TIPO_LOTE,
    COL_NUM_LOTE,
    COL_NUM_RECIBO,
    COL_FECHA_COBRO,
    COL_IMPORTE,
    COL_JUZGADO,
    COL_ANIO_EXP,
    COL_EXP,
    COL_OFICINA_COD,
    COL_NUM_ACTA,
    COL_FECHA_LABRADA,
    COL_DOC_INFRACTOR,
    COL_NOMBRE_INFRACTOR,
    COL_PADRON,
]